fix: move ffmpeg to correct folder after extract
nwutils/nw-builder pull request #917
Opened 2023-08-10 10:40 UTC by zkrige

Fixes: #916 

## Description
reinstate the `replaceFfmpeg` code that was removed during cleanup

2023-08-10 15:50 UTC, ayushmanchhabra requested changes
Thanks for this! One case where this fails is when `ffmpeg` is false and there is a binary cached. Enabling `ffmpeg` does not download it since it thinks its already "cached".

Maybe we can add this [here](https://github.com/nwutils/nw-builder/blob/5726a7ec7ad5fa78e12f53dd9eeb8f58a9c8833d/src/get.js#L125):
```patch
- if (nwCached === false) {
+if (nwCached === false || ffmpeg === true) { 
```

2023-08-10 16:13 UTC, zkrige commented
It needs to be a little bit smarter otherwise it will download ffmpeg every time. we only want to download ffmpeg if it hasn't been downloaded.

your solution will for for now, but ideally it should check if ffmpeg must be downloaded

2023-08-10 16:23 UTC, ayushmanchhabra approved these changes

2023-08-10 16:23 UTC, merged

2023-08-11 07:56 UTC, zkrige commented
@ayushmanchhabra hmmm this is still broken

`await replaceFfmpeg(platform, nwDir, out);`

just ends up copying the zip file over itself. We need some way to get the extracted filename