docs: update docs
nwutils/nw-builder pull request #980
Opened 2023-11-15 12:48 UTC by TinsFox

# Update docs

## Description
As a new user, I prefer to see how it was done in the beginning rather than upgrading the documentation. This can feel strange to new users

2023-11-15 15:57 UTC, ayushmanchhabra commented
I recently moved all documentation from README to JSDoc comments so that it can be autogenerated as a website. I don't really see an issue with not having install instructions on the README if a link to a docs site is given.

2023-11-15 16:11 UTC, sysrage requested changes
I do agree basic usage instructions should be included in the README. The documentation can/should be used more as an API reference if/when basic usage isn't enough.

2023-11-15 16:11 UTC, sysrage commented on README.md
> +    nwbuild --mode=get
Wrong flag for "run".

2023-11-15 16:11 UTC, sysrage commented on README.md
> +      srcDir: "./nwapp/**/* ./other/**/*.js",
Is this correct? I don't use globs, but why is this a space-separated string rather than an array of globs?

2023-11-15 16:20 UTC, ayushmanchhabra commented
What do you mean by basic usage? I'm guess I'm too familiar with the options so everything to me seems like basic usage to me :P

2023-11-16 02:49 UTC, TinsFox commented
> What do you mean by basic usage? I'm guess I'm too familiar with the options so everything to me seems like basic usage to me :P

It's how to use the library quickly to get him to do something that's expected. Just the most basic configuration is fine, probably the effect of a command like 'nwbuild --mode=build', if this command automatically fills in the other default parameters

2023-11-16 02:58 UTC, TinsFox commented
> I recently moved all documentation from README to JSDoc comments so that it can be autogenerated as a website. I don't really see an issue with not having install instructions on the README if a link to a docs site is given.

I see that, but I recommend removing this line

https://github.com/nwutils/nw-builder/blob/3e367f383d439b850500bdffae641f83032014e8/.gitignore#L11

 because keeping the Markdown file allows us to add some extra instructions to it, rather than completely handing it over to the program

2023-11-17 16:19 UTC, ayushmanchhabra commented
> > I recently moved all documentation from README to JSDoc comments so that it can be autogenerated as a website. I don't really see an issue with not having install instructions on the README if a link to a docs site is given.
> 
> I see that, but I recommend removing this line
> 
> https://github.com/nwutils/nw-builder/blob/3e367f383d439b850500bdffae641f83032014e8/.gitignore#L11
> 
> because keeping the Markdown file allows us to add some extra instructions to it, rather than completely handing it over to the program

I understand what you mean. This is how I initially managed the docs. I'm trying to automate as many things as I can so that the maintainer(s) after me will have it easier.

2023-11-24 15:19 UTC, ayushmanchhabra commented
@TinsFox I've made a couple of commit suggestions

2023-11-26 09:17 UTC, TinsFox commented
> @TinsFox I've made a couple of commit suggestions

I can't see your comment. Did you forget to submit it?

2023-11-26 14:42 UTC, ayushmanchhabra approved these changes
I'm fine with the changes here. I have to figure out how to setup docs nicely which I'll do in subsequent PRs.

2023-11-26 14:43 UTC, merged